# Project information
site_name: 100askTeam eLinux Code Library
site_url: https://github.com/100askTeam/LinuxCodeLibrary.git
site_author: 100askTeam
site_description: >-
  100ASKTeam boards Start Page.
copyright: Copyright &copy; 2008 - 2022 100ask Team
edit_uri: edit/master/docs/
#edit_uri: https://github.com/100askTeam/TutorialCo-creation/tree/master/docs
repo_url: https://github.com/100askTeam/LinuxCodeLibrary
repo_name: 100askTeam/LinuxCodeLibrary

# Configuration
theme:
  name: material
  custom_dir: overrides
  # Static files
  static_templates:
    - 404.html
  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    - content.code.annotate
    # - content.tabs.link
    - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: favicon.png
  icon:
    logo: dsp-logo

# Plugins
plugins:
  - search
  - markmap:
      base_path: docs
      encoding: utf-8
      file_extension: .mm.md
      d3_version: 6.7.0
      lib_version: 0.14.1
      view_version: 0.14.0 
#  - offline  
  - minify:
      minify_html: true
#  - social:
#      cards_color:
#        fill: "#0FF1CE" 
#        text: "#FFFFFF"
  - search:
      jieba_dict: dict.txt 
extra:
  analytics:
    provider: google
    property: G-LZX4K52CZ1
  homepage: https://code.100ask.net
  alternate:
    - name: 中文简体
      link: /
      lang: zh  
    - name: English
      link: /en/ 
      lang: en

      
#  disqus: dongshanpi-com

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables  
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify  
  - toc:
      permalink: true
  - toc:
      title: On this page
  - toc:
      permalink_title: Anchor link to this section for reference
  - toc:
      toc_depth: 3      
  - pymdownx.arithmatex:
      generic: true        
  - pymdownx.arithmatex:
      generic: true

  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true   
  - pymdownx.snippets      
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - def_list      
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  
# Page tree
nav:
  - 站点介绍:
    - 简述: index.md
    - LinuxC基础: '01-LinuxCprogrammers.md'
    - Linux组件开发: '02-Components.md'
    - Linux设备驱动开发: '03-DeviceDriver.md'
    - Linux系统开发: '04-System.md'
  - LinuxC基础编程:
    - LinuxShell:
      - 文件管理类命令: 'Stage1-LinuxCprogrammers/LinuxShell/Filemanagement.md'
      - 文档编辑类命令: 'Stage1-LinuxCprogrammers/LinuxShell/DocumentEditing.md'
      - 系统管理: 'Stage1-LinuxCprogrammers/LinuxShell/SystemManagement.md' 
      - 磁盘操作: 'Stage1-LinuxCprogrammers/LinuxShell/DiskOperation.md'
      - 网络管理: 'Stage1-LinuxCprogrammers/LinuxShell/NetworkManagement.md'  
    - C基础知识:
      - C基础: 'Stage1-LinuxCprogrammers/01-Introduction.md'
      - 编译链接: 'Stage1-LinuxCprogrammers/01-Introduction.md'
    - MakeFile:
      - Makefile简述: 'Stage1-LinuxCprogrammers/MakeFile/01-Introduction.md'
      - Makefile规则: 'Stage1-LinuxCprogrammers/MakeFile/02-regulation.md'
      - Makefile变量: 'Stage1-LinuxCprogrammers/MakeFile/03-variable.md'
      - Makefile模式规则与伪目标: 'Stage1-LinuxCprogrammers/MakeFile/04-Pattern_rules_pseudo-targets.md'
      - Makefile函数: 'Stage1-LinuxCprogrammers/MakeFile/05-function.md'
      - Makefile实例: 'Stage1-LinuxCprogrammers/MakeFile/06-examples.md'
    - GNU工具:
      - GCC: 'Stage1-LinuxCprogrammers/GNU/01-Introduction.md'
      - G++: 'Stage1-LinuxCprogrammers/GNU/01-Introduction.md'
      - GDB: 'Stage1-LinuxCprogrammers/GNU/01-Introduction.md'
      - OBJDUMP: 'Stage1-LinuxCprogrammers/GNU/01-Introduction.md'
    - 文件/IO:
      - C基础: 'Stage1-LinuxCprogrammers/CFileinputoutput/01-Introduction.md'    
    - 进程线程:
      - C基础: 'Stage1-LinuxCprogrammers/ProcessThread/01-Introduction.md'    
    - 进程通信:
      - C基础: 'Stage1-LinuxCprogrammers/01-Introduction.md'    
    - 网络编程:
      - C基础: 'Stage1-LinuxCprogrammers/01-Introduction.md'    
    - 正则表达式:
      - C基础: 'Stage1-LinuxCprogrammers/01-Introduction.md'    
  - Linux组件开发:
    - 音频显示组件: 'Stage2-Components/AudioAndVideoApplications.md' 
    - LVGL组件: 
      - 简述: 'Stage2-Components/01-Introduction.md' 
      - 6ULLPro-开发示例: 'Stage2-Components/01-Introduction.md'
      - MP157Pro-开发示例: 'Stage2-Components/01-Introduction.md'
    - 网络组件: 'Stage2-Components/NetworkingApplications.md'
    - MQTT组件:
      - 简述: 'Stage2-Components/NetworkingApplications/MQTT/01-Introduction.md'
      - 6ULLPro-开发示例: 'Stage2-Components/NetworkingApplications/MQTT/6ULLPro-Example.md' 
      - MP157Pro-开发示例: 'Stage2-Components/NetworkingApplications/MQTT/MP157Pro-Example.md'
  - 设备驱动开发:
    -NXP-GPIO子系统:
      - 6ULLPro-LED灯: 'Stage3-DeviceDriver/Nxp/IMX6ULL/Pro/01-leddriver.md'
      - 6ULLPro-按键: 'Stage3-DeviceDriver/Nxp/IMX6ULL/Pro/02-keydriver.md'
      - 6ULLPro-SR501:  'Stage3-DeviceDriver/Nxp/IMX6ULL/Pro/03-sr501driver.md'
      - 6ULLPro-SR04:  'Stage3-DeviceDriver/Nxp/IMX6ULL/Pro/04-SR04driver.md'
      - 6ULLPro-DS18B20: 'Stage3-DeviceDriver/Nxp/IMX6ULL/Pro/06-ds18b20driver.md'
      - 6ULLPro-DHT11:  'Stage3-DeviceDriver/Nxp/IMX6ULL/Pro/05-dht11driver.md'
      - 6ULLPro-HS0038:  'Stage3-DeviceDriver/Nxp/IMX6ULL/Pro/07-hs0038driver.md'
    - ST-GPIO子系统:      
      - MP157Pro-LED灯: 'Stage3-DeviceDriver/St/STM32MP157/Pro/01-leddriver.md'
      - MP157Pro-按键: 'Stage3-DeviceDriver/St/STM32MP157/Pro/02-keydriver.md'
      - MP157Pro-SR501:  'Stage3-DeviceDriver/St/STM32MP157/Pro/03-sr501driver.md'
      - MP157Pro-SR04:  'Stage3-DeviceDriver/St/STM32MP157/Pro/04-SR04driver.md'
      - MP157Pro-DS18B20: 'Stage3-DeviceDriver/St/STM32MP157/Pro/06-ds18b20driver.md'
      - MP157Pro-DHT11:  'Stage3-DeviceDriver/St/STM32MP157/Pro/05-dht11driver.md'
      - MP157Pro-HS0038:  'Stage3-DeviceDriver/St/STM32MP157/Pro/07-hs0038driver.md'     
    - NXP-I2C子系统:
      - 简述: 'Stage3-DeviceDriver/01-Introduction.md'
      - 6ULLPro-AT24c02模块:  'Stage3-DeviceDriver/Nxp/IMX6ULL/Pro/08-at24c02driver.md'
    - ST-I2C子系统:
      - 简述: 'Stage3-DeviceDriver/01-Introduction.md'
      - MP157Pro-AT24c02模块:  'Stage3-DeviceDriver/St/STM32MP157/Pro/08-at24c02driver.md'
    - NXP-SPI子系统:
      - 简述: 'Stage3-DeviceDriver/01-Introduction.md' 
      - 6ULLPro-OLED: 'Stage3-DeviceDriver/Nxp/IMX6ULL/Pro/09-oleddriver.md'
      - 6ULLPro-DAC模块: 'Stage3-DeviceDriver/Nxp/IMX6ULL/Pro/10-dacdriver.md'
    - ST-SPI子系统:
      - 简述: 'Stage3-DeviceDriver/01-Introduction.md' 
      - MP157Pro-OLED: 'Stage3-DeviceDriver/St/STM32MP157/Pro/09-oleddriver.md'
      - MP157Pro-DAC模块: 'Stage3-DeviceDriver/St/STM32MP157/Pro/10-dacdriver.md'      

  - 系统开发: 
    - Git工具使用:
      - 简述: 'Stage4-System/01-Introduction.md' 
    - NXP系统:
      - 简述: 'Stage4-System/01-Introduction.md' 
      - IMX6ULLPro: 'Stage4-System/01-Introduction.md'
      - IMX6ULLMini: 'Stage4-System/01-Introduction.md'
    - ST系统:
      - 简述: 'Stage4-System/01-Introduction.md' 
      - STM32MP157Pro: 'Stage4-System/01-Introduction.md'
    - 全志系统:
      - 简述: 'Stage4-System/01-Introduction.md' 
      - 东山哪吒D1-H: 'Stage4-System/01-Introduction.md'
      - T113Pro: 'Stage4-System/01-Introduction.md'
      - V853: 'Stage4-System/01-Introduction.md'      
    - 星宸系统:
      - 简述: 'Stage4-System/01-Introduction.md' 
      - SSD202Pro: 'Stage4-System/01-Introduction.md'            


extra_javascript:
  - javascripts/shortcuts.js

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/d3@6.7.0/dist/d3.min.js
  - https://unpkg.com/markmap-lib@0.14.1/dist/browser/index.min.js
  - https://unpkg.com/markmap-view@0.14.0/dist/index.min.js  
