# Project information
site_name: 百问网文档共创站点
site_url: https://github.com/100askTeam/TutorialCo-creation.git
site_author: 100askTeam
site_description: >-
  100ASKTeam boards Start Page.
copyright: Copyright &copy; 2008 - 2022 100ask Team
edit_uri: edit/master/docs/
#edit_uri: https://github.com/100askTeam/TutorialCo-creation/tree/master/docs
repo_url: https://github.com/100askTeam/TutorialCo-creation
repo_name: 100askTeam/TutorialCo-creation

# Configuration
theme:
  name: material
  custom_dir: overrides
  # Static files
  static_templates:
    - 404.html
  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    - content.code.annotate
    # - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: favicon.png
  icon:
    logo: dsp-logo

# Plugins
plugins:
  - search
  - markmap:
      base_path: docs
      encoding: utf-8
      file_extension: .mm.md
      d3_version: 6.7.0
      lib_version: 0.14.1
      view_version: 0.14.0 
#  - offline  
  - minify:
      minify_html: true
#  - social:
#      cards_color:
#        fill: "#0FF1CE" 
#        text: "#FFFFFF"

extra:
  analytics:
    provider: google
    property: G-LZX4K52CZ1
  homepage: https://lib.100ask.net
  alternate:
    - name: 中文简体
      link: /
      lang: zh  
    - name: English
      link: /en/ 
      lang: en

      
#  disqus: dongshanpi-com

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables  
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify  
  - toc:
      permalink: true
  - toc:
      title: On this page
  - toc:
      permalink_title: Anchor link to this section for reference
  - toc:
      toc_depth: 3      
  - pymdownx.arithmatex:
      generic: true        
  - pymdownx.arithmatex:
      generic: true

  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true   
  - pymdownx.snippets      
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true               
  
# Page tree
nav:
  - 站点介绍:
    - 简述: index.md
    - LinuxC基础: '01-LinuxCprogrammers.md'
    - 应用组件开发: '02-Components.md'
    - 设备驱动开发: '03-DeviceDriver.md'
    - 系统开发: '04-System.md'
  - LinuxC基础编程:
    - C基础知识:
      - C基础: 'Stage1-LinuxCprogrammers/01-Introduction.md'
      - 编译链接: 'Stage1-LinuxCprogrammers/01-Introduction.md'
    - GCC编译器:
      - 测试页面1: 'Stage1-LinuxCprogrammers/01-Introduction.md'
      - 编译链接: 'Stage1-LinuxCprogrammers/01-Introduction.md'      
    - Makefile:
      - 测试页面1: 'Stage1-LinuxCprogrammers/01-Introduction.md'
      - 编译链接: 'Stage1-LinuxCprogrammers/01-Introduction.md'      
    - 文件与IO操作:
      - 测试页面1: 'Stage1-LinuxCprogrammers/01-Introduction.md'
      - 测试页面1: 'Stage1-LinuxCprogrammers/01-Introduction.md'
    - Shell编程:
      - 测试页面1: 'Stage1-LinuxCprogrammers/01-Introduction.md'
      - 测试页面1: 'Stage1-LinuxCprogrammers/01-Introduction.md'
    - 正则表达式:
      - 测试页面1: 'Stage1-LinuxCprogrammers/01-Introduction.md'
      - 测试页面1: 'Stage1-LinuxCprogrammers/01-Introduction.md'      
    - 进程线程:
      - 测试页面1: 'Stage1-LinuxCprogrammers/01-Introduction.md'
      - 测试页面1: 'Stage1-LinuxCprogrammers/01-Introduction.md'      
    - 进程通信:
      - 测试页面1: 'Stage1-LinuxCprogrammers/01-Introduction.md'
      - 测试页面1: 'Stage1-LinuxCprogrammers/01-Introduction.md'      
    - 网络编程:
      - 测试页面1: 'Stage1-LinuxCprogrammers/01-Introduction.md'
      - 测试页面1: 'Stage1-LinuxCprogrammers/01-Introduction.md'

  - 应用组件开发:
    - 显示系列组件: 'Stage2-Components/01-Introduction.md' 
    - LVGL组件: 
      - 简述: 'Stage2-Components/01-Introduction.md' 
      - 开发示例: 'Stage2-Components/01-Introduction.md'
    - SDL组件: 
      - 简述: 'Stage2-Components/01-Introduction.md' 
      - 开发示例: 'Stage2-Components/01-Introduction.md'
    - Wayland组件: 
      - 简述: 'Stage2-Components/01-Introduction.md' 
      - 开发示例: 'Stage2-Components/01-Introduction.md'
    - QT5组件: 
      - 简述: 'Stage2-Components/01-Introduction.md' 
      - 开发示例: 'Stage2-Components/01-Introduction.md'      
    - 网络系列组件: 'Stage2-Components/01-Introduction.md'
    - MQTT组件:
      - 简述: 'Stage2-Components/01-Introduction.md'
      - 开发示例: 'Stage2-Components/01-Introduction.md'
    - libnl组件:
      - 简述: 'Stage2-Components/01-Introduction.md'
      - 开发示例: 'Stage2-Components/01-Introduction.md'
    - WPA组件:
      - 简述: 'Stage2-Components/01-Introduction.md'
      - 开发示例: 'Stage2-Components/01-Introduction.md'
    - BlueZ组件:
      - 简述: 'Stage2-Components/01-Introduction.md'
      - 开发示例: 'Stage2-Components/01-Introduction.md'      
  - 设备驱动开发:
    - Pinctrl子系统:
      - 简述: 'Stage3-DeviceDriver/01-Introduction.md' 
      - LED灯: 'Stage3-DeviceDriver/01-Introduction.md'
      - KEY按键: 'Stage3-DeviceDriver/01-Introduction.md'  
    - GPIO子系统:
      - 简述: 'Stage3-DeviceDriver/01-Introduction.md' 
      - LED灯: 'Stage3-DeviceDriver/01-Introduction.md'
      - KEY按键: 'Stage3-DeviceDriver/01-Introduction.md'
    - I2C子系统:
      - 简述: 'Stage3-DeviceDriver/01-Introduction.md' 
      - SSD1306-OLED: 'Stage3-DeviceDriver/01-Introduction.md'
      - GT911触摸屏: 'Stage3-DeviceDriver/01-Introduction.md'
    - Interrupt子系统:
      - 简述: 'Stage3-DeviceDriver/01-Introduction.md' 
      - SPI-LCD: 'Stage3-DeviceDriver/01-Introduction.md'
      - ADX135: 'Stage3-DeviceDriver/01-Introduction.md'            
    - SPI子系统:
      - 简述: 'Stage3-DeviceDriver/01-Introduction.md' 
      - SPI-LCD: 'Stage3-DeviceDriver/01-Introduction.md'
      - ADX135: 'Stage3-DeviceDriver/01-Introduction.md'
    - Input子系统:
      - 简述: 'Stage3-DeviceDriver/01-Introduction.md' 
      - SPI-LCD: 'Stage3-DeviceDriver/01-Introduction.md'
      - ADX135: 'Stage3-DeviceDriver/01-Introduction.md'      
    - UART子系统:
      - 简述: 'Stage3-DeviceDriver/01-Introduction.md' 
      - SPI-LCD: 'Stage3-DeviceDriver/01-Introduction.md'
      - ADX135: 'Stage3-DeviceDriver/01-Introduction.md'
    - PCI/PCI-e子系统:
      - 简述: 'Stage3-DeviceDriver/01-Introduction.md' 
      - SPI-LCD: 'Stage3-DeviceDriver/01-Introduction.md'
      - ADX135: 'Stage3-DeviceDriver/01-Introduction.md'      
    - LCD驱动:
      - 简述: 'Stage3-DeviceDriver/01-Introduction.md' 
      - RGB-LCD: 'Stage3-DeviceDriver/01-Introduction.md'
      - MIPI-LCD: 'Stage3-DeviceDriver/01-Introduction.md'

  - 系统开发: 
    - NXP系统:
      - 简述: 'Stage4-System/01-Introduction.md' 
      - IMX6ULL: 'Stage4-System/01-Introduction.md'
    - ST系统:
      - 简述: 'Stage4-System/01-Introduction.md' 
      - STM32MP1: 'Stage4-System/01-Introduction.md'
    - 全志系统:
      - 简述: 'Stage4-System/01-Introduction.md' 
      - D1-H: 'Stage4-System/01-Introduction.md'
      - D1s: 'Stage4-System/01-Introduction.md'
      - T113: 'Stage4-System/01-Introduction.md'
      - V853: 'Stage4-System/01-Introduction.md'      
    - 星宸系统:
      - 简述: 'Stage4-System/01-Introduction.md' 
      - SSD202: 'Stage4-System/01-Introduction.md'            


extra_javascript:
  - javascripts/shortcuts.js

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/d3@6.7.0/dist/d3.min.js
  - https://unpkg.com/markmap-lib@0.14.1/dist/browser/index.min.js
  - https://unpkg.com/markmap-view@0.14.0/dist/index.min.js  